### ISSUE TITLE
Burp crash

### ISSUE THREAD

**Issue by Teicu** [yandex/burp-molly-pack#2]
Hi, 

my Burp is installed on Mac OS, can you explain me please how to use your plugin?  Because if I install the jar from extender it crash. 

not sure how I can open it using  java -jar /Applications/Burp Suite Professional.app because not works.  Thank you

**Comment by andrewaeva** [comment]
Hi,

`cd /Applications/Burp Suite Professional.app/Contents/java/app`
and then
`java -jar burpsuite_pro.jar`

**Comment by Teicu** [comment]
ok, so it is right if I use the following cmd? 

so java -jar /Applications/Burp\ Suite\ Professional.app/Contents/java/app/burpsuite_pro.jar /Users/Desktop/MOLLY_CONFIG/src/main/config/burp_molly_config.json

**Comment by andrewaeva** [comment]
No,

`export MOLLY_CONFIG=/path/to/burp_molly_config.json`
then
` java -jar /Applications/Burp\ Suite\ Professional.app/Contents/java/app/burpsuite_pro.jar `

**Comment by locpv-ibl** [comment]
Still crash regardless of installing successfully :-1:
