### ISSUE TITLE
SSRF/XXE/HTTP interaction not working on v2.1

### ISSUE THREAD

**Issue by ghost** [yandex/burp-molly-pack#3]
I've been testing this extension on 1.7.37 and 2.1 versions.
In version 1.7.37 extension works.
in 2.1 it works but not the active payloads.
I've tested on testphp.vulnweb.com and DSVW (https://github.com/stamparm/DSVW).
With older version the ssrf http/dns interaction are detected, in newer one it doesn't.
Maybe due to API changes, 'cause also active phase of other extensions doesn't works.
Would like a possible update 'cause i don't know well Java (i'll try).
Or someone could help.

Cheers

**Comment by andrewaeva** [comment]
Add to scan this uri http://testphp.vulnweb.com/showimage.php?file=abc
Plugin works fine.

**Comment by ghost** [comment]
Hi, actually i've used it also on testphp.vulnweb.com and i don't get SSRF DNS alert nor the SSRF HTTP alert.
Running Burp Suite Professional 2.1
Extension loaded but seems to not run? I'm not understanding this situation, so i've asked some infos and tips to PortSwigger team.

**Comment by ghost** [comment]
Resolved
